name: E2E Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        # Keep in sync with package.json -> packageManager
        version: 10.13.1
        run_install: false
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
      
    - name: Build web application
      run: pnpm web:build
      
    - name: Run Playwright tests
      run: pnpm test:e2e
      
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-results
        path: test-results/
        retention-days: 30